### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Cujoko** [Cujoko-Dev/git-hooks-1c#1]
```
d:\Dev\1С\evotor-1c-7 (dev)
(evotor-1c-7) λ git commit
fatal: Unable to write new index file
[19-05-05 09:30:12,193][git_hooks_1c.pre_commit:92][ERROR] Command '['git', 'add', '--all', 'd:\\Dev\\1С\\evotor-1c-7\\ExtForms\\cjk-evotor_ert_src']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 88, in run
    add_to_index(for_indexing_source_dir_fullpaths)
  File "d:\dev\python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 67, in add_to_index
    exit_code = subprocess.check_call(args_au)
  File "c:\program files (x86)\python37\Lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'add', '--all', 'd:\\Dev\\1С\\evotor-1c-7\\ExtForms\\cjk-evotor_ert_src']' returned non-zero exit status 128.
Aborting commit due to empty commit message.

d:\Dev\1С\evotor-1c-7 (dev)
(evotor-1c-7) λ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   ExtForms/cjk-evotor-setting.ert
        modified:   ExtForms/cjk-evotor-setting_ert_src/МодульФормы.1s
        deleted:    ExtForms/cjk-evotor-setting_ert_src/ПорядокОбъектов.ord
        deleted:    ExtForms/cjk-evotor-setting_ert_src/Таблица.mxl
        modified:   ExtForms/cjk-evotor-setting_ert_src/Форма.frm
        new file:   ExtForms/cjk-evotor-starter.ert
        new file:   ExtForms/cjk-evotor.ert

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ExtForms/cjk-evotor_ert_src/МодульФормы.1s


d:\Dev\1С\evotor-1c-7 (dev)
(evotor-1c-7) λ git add .

d:\Dev\1С\evotor-1c-7 (dev)
(evotor-1c-7) λ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   ExtForms/cjk-evotor-setting.ert
        modified:   ExtForms/cjk-evotor-setting_ert_src/МодульФормы.1s
        deleted:    ExtForms/cjk-evotor-setting_ert_src/ПорядокОбъектов.ord
        deleted:    ExtForms/cjk-evotor-setting_ert_src/Таблица.mxl
        modified:   ExtForms/cjk-evotor-setting_ert_src/Форма.frm
        new file:   ExtForms/cjk-evotor-starter.ert
        new file:   ExtForms/cjk-evotor.ert
        modified:   ExtForms/cjk-evotor_ert_src/МодульФормы.1s
```

**Comment by cujoko** [comment]
Вроде уже не актуально.
