### ISSUE TITLE
git('rm', '--cached', str(file_fullpath)) иногда завершается с ошибкой

### ISSUE THREAD

**Issue by cujoko** [Cujoko-Dev/git-hooks-1c#4]
```
2021-01-01 18:28:58.274 | ERROR    | git_hooks_1c.pre_commit:run:104 - Unexpected exit code: 128
Command line: | 'C:\Program Files\Git\mingw64\libexec\git-core\git.exe' rm --cached 'D:\Dev\1С\evotor-1c-8-sd\cjk-evotor-sd-a-unf-16.epf'
Stdout:       | rm 'cjk-evotor-sd-a-unf-16.epf'
Stderr:       | fatal: Unable to write new index file
Traceback (most recent call last):

  File "C:\Users\Cujoko\Envs\git-hooks-1c\Scripts\gh1c", line 5, in <module>
    run()
    └ <function run at 0x000001BDD52E4940>

  File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\core.py", line 13, in run
    args.func(args)
    │    │    └ Namespace(level=None, log_file=None, log_file_level=None, subparser_name='pre-commit', keep_files=False, func=<function run a...
    │    └ <function run at 0x000001BDD5997430>
    └ Namespace(level=None, log_file=None, log_file_level=None, subparser_name='pre-commit', keep_files=False, func=<function run a...

> File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 102, in run
    remove_from_index(for_processing_file_fullpaths)
    │                 └ [WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-bp-30.epf'), WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-com...
    └ <function remove_from_index at 0x000001BDD59973A0>

  File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 74, in remove_from_index
    git('rm', '--cached', str(file_fullpath))
    │                         └ WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-unf-16.epf')
    └ LocalCommand(C:\Program Files\Git\mingw64\libexec\git-core\git.exe)

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
           │    │   │       └ {}
           │    │   └ ('rm', '--cached', 'D:\\Dev\\1С\\evotor-1c-8-sd\\cjk-evotor-sd-a-unf-16.epf')
           │    └ <function BaseCommand.run at 0x000001BDD57A3D30>
           └ LocalCommand(C:\Program Files\Git\mingw64\libexec\git-core\git.exe)

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 232, in run
    return p.run()
           └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
           │        │  │        └ None
           │        │  └ 0
           │        └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>
           └ <function run_proc at 0x000001BDD5796AF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           │              │     │        │        │       └ 'fatal: Unable to write new index file\n'
           │              │     │        │        └ "rm 'cjk-evotor-sd-a-unf-16.epf'\n"
           │              │     │        └ None
           │              │     └ 0
           │              └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>
           └ <function _check_process at 0x000001BDD5780550>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
    │    │      │        │        │       └ 'fatal: Unable to write new index file\n'
    │    │      │        │        └ "rm 'cjk-evotor-sd-a-unf-16.epf'\n"
    │    │      │        └ None
    │    │      └ 0
    │    └ <function PopenAddons.verify at 0x000001BDD58CFA60>
    └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\machines\base.py", line 24, in verify
    raise ProcessExecutionError(
          └ <class 'plumbum.commands.processes.ProcessExecutionError'>

plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | 'C:\Program Files\Git\mingw64\libexec\git-core\git.exe' rm --cached 'D:\Dev\1С\evotor-1c-8-sd\cjk-evotor-sd-a-unf-16.epf'
Stdout:       | rm 'cjk-evotor-sd-a-unf-16.epf'
Stderr:       | fatal: Unable to write new index file
```

**Comment by Cujoko** [comment]
Но когда я запустил в отладчике и прошёл этот код пошагово, всё завершилось успешно.

**Comment by Cujoko** [comment]
```
2021-01-01 18:28:58.274 | ERROR    | git_hooks_1c.pre_commit:run:104 - Unexpected exit code: 128
Command line: | 'C:\Program Files\Git\mingw64\libexec\git-core\git.exe' rm --cached 'D:\Dev\1С\evotor-1c-8-sd\cjk-evotor-sd-a-unf-16.epf'
Stdout:       | rm 'cjk-evotor-sd-a-unf-16.epf'
Stderr:       | fatal: Unable to write new index file
Traceback (most recent call last):

  File "C:\Users\Cujoko\Envs\git-hooks-1c\Scripts\gh1c", line 5, in <module>
    run()
    └ <function run at 0x000001BDD52E4940>

  File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\core.py", line 13, in run
    args.func(args)
    │    │    └ Namespace(level=None, log_file=None, log_file_level=None, subparser_name='pre-commit', keep_files=False, func=<function run a...
    │    └ <function run at 0x000001BDD5997430>
    └ Namespace(level=None, log_file=None, log_file_level=None, subparser_name='pre-commit', keep_files=False, func=<function run a...

> File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 102, in run
    remove_from_index(for_processing_file_fullpaths)
    │                 └ [WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-bp-30.epf'), WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-com...
    └ <function remove_from_index at 0x000001BDD59973A0>

  File "D:\Dev\Python\git-hooks-1c\git_hooks_1c\pre_commit.py", line 74, in remove_from_index
    git('rm', '--cached', str(file_fullpath))
    │                         └ WindowsPath('D:/Dev/1С/evotor-1c-8-sd/cjk-evotor-sd-a-unf-16.epf')
    └ LocalCommand(C:\Program Files\Git\mingw64\libexec\git-core\git.exe)

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
           │    │   │       └ {}
           │    │   └ ('rm', '--cached', 'D:\\Dev\\1С\\evotor-1c-8-sd\\cjk-evotor-sd-a-unf-16.epf')
           │    └ <function BaseCommand.run at 0x000001BDD57A3D30>
           └ LocalCommand(C:\Program Files\Git\mingw64\libexec\git-core\git.exe)

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 232, in run
    return p.run()
           └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
           │        │  │        └ None
           │        │  └ 0
           │        └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>
           └ <function run_proc at 0x000001BDD5796AF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
           │              │     │        │        │       └ 'fatal: Unable to write new index file\n'
           │              │     │        │        └ "rm 'cjk-evotor-sd-a-unf-16.epf'\n"
           │              │     │        └ None
           │              │     └ 0
           │              └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>
           └ <function _check_process at 0x000001BDD5780550>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\commands\processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
    │    │      │        │        │       └ 'fatal: Unable to write new index file\n'
    │    │      │        │        └ "rm 'cjk-evotor-sd-a-unf-16.epf'\n"
    │    │      │        └ None
    │    │      └ 0
    │    └ <function PopenAddons.verify at 0x000001BDD58CFA60>
    └ <plumbum.machines.local.PlumbumLocalPopen object at 0x000001BDD3444DF0>

  File "C:\Users\Cujoko\Envs\git-hooks-1c\lib\site-packages\plumbum\machines\base.py", line 24, in verify
    raise ProcessExecutionError(
          └ <class 'plumbum.commands.processes.ProcessExecutionError'>

plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | 'C:\Program Files\Git\mingw64\libexec\git-core\git.exe' rm --cached 'D:\Dev\1С\evotor-1c-8-sd\cjk-evotor-sd-a-unf-16.epf'
Stdout:       | rm 'cjk-evotor-sd-a-unf-16.epf'
Stderr:       | fatal: Unable to write new index file
```
